version: "3"

services:
  database:
    container_name: database
    build:
      context: database
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    networks:
      - podcastindex

  blockstorage:
    container_name: blockstorage
    build:
      context: blockstorage
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9000:9000
    networks:
      - podcastindex

  bus:
    container_name: bus
    build:
      context: bus
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9092:9092
    networks:
      - podcastindex

networks:
  podcastindex:
    driver: bridge
