[tool.poetry]
name = "aggregator-etl"
version = "0.0.1"
description = ""
authors = ["sarastinishi <sarasti.nishi@protonmail.ch>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
