# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master ]

jobs:
  test-aggrivate:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: aggrivate_test
          MYSQL_USER: aggrivate_test
          MYSQL_PASSWORD: aggrivate_test
          MYSQL_ROOT_PASSWORD: aggrivate_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    defaults:
      run:
        working-directory: aggrivate
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      MYSQL_DATABASE: aggrivate_test
      MYSQL_USER: aggrivate_test
      MYSQL_PASSWORD: aggrivate_test
      MYSQL_HOST: 127.0.0.1
    steps:
    - uses: actions/checkout@v2
    - name: Grant database privileges
      run: mysql --port 3306 -u root -p aggrivate_test --execute "GRANT ALL ON *.* TO 'aggrivate_test'@'%' with grant option; FLUSH PRIVILEGES;"
    - name: Setup Database
      run: mysql -u $MYSQL_USER -p $MYSQL_PASSWORD < "test/initdb.sql"; 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - run: npm run build --if-present
    - run: npm run test:ci
